#! /bin/bash

date=`date +%Y-%m-%d_%H`

echo "lets do this";

# create the backup file 
ssh -i /home/chris/.ssh/id_rsa linode "/srv/flightloggin/make-fixtures";

echo "after ssh";

# copy the dump to the local project dir
scp -i /home/chris/.ssh/id_rsa linode:/srv/flightloggin/dump /srv/flightloggin/dumps/${date}.dump;
echo "after scp";

exit 0;
