#! /bin/bash

date=`date +%Y-%m-%d`
myfilename="mysql-${date}.sql.bz2"

echo "lets do this";

# clean up the database, and create the backup file
ssh chris@flightlogg.in "~/bin/mysql-clean; ~/bin/mysql-backup; /srv/flightloggin/make-fixtures";

# copy mysql backup file to local machine
scp chris@flightlogg.in:~/backups/${myfilename} /storage/mysql;

# copy flightloggin django fixtures and sql files to the local project dir
scp chris@flightlogg.in:/srv/flightloggin/fixtures/* /srv/flightloggin/fixtures;

# delete the mysql backup file from the remote server (to save space)
ssh chris@flightlogg.in "rm ~/backups/${myfilename}";

exit
