#! /bin/bash

# only let thi script run on the development server (chris-comp), 
# otherwise it will clear the production database, and that would not be good

if [ $(hostname) != 'chris-desktop' ]
then
    echo "not chris-desktop";
    exit
fi

NEWEST=
for f in /srv/flightloggin/dumps/*.dump
do
    if [ -z "$NEWEST" ]
    then 
        NEWEST=$f
    elif [ "$f" -nt "$NEWEST" ] 
    then
        NEWEST=$f
    fi
done

echo "$NEWEST";
pg_restore "$NEWEST" --clean -U chris -d logbook

exit
