#! /bin/bash

# only let thi script run on the development server (chris-comp), 
# otherwise it will clear the production database, and that would not be good

if [ $(hostname) != 'chris-comp' ]
then
    echo "not chris-comp";
    exit
fi

bunzip2 master_dump.sql.bz2
echo "unzip complete"
psql -U postgres < master_dump.sql

exit
