#! /bin/bash

echo "contenttypes";
/srv/flightloggin/manage.py dumpdata contenttypes | bzip2 > /srv/flightloggin/fixtures/ct.json.bz2;

echo "auth";
/srv/flightloggin/manage.py dumpdata auth | bzip2 > /srv/flightloggin/fixtures/auth.json.bz2;

echo "plane";
/srv/flightloggin/manage.py dumpdata plane | bzip2 > /srv/flightloggin/fixtures/plane.json.bz2;

echo "records";
/srv/flightloggin/manage.py dumpdata records | bzip2 > /srv/flightloggin/fixtures/records.json.bz2;

echo "profiles";
/srv/flightloggin/manage.py dumpdata profile | bzip2 > /srv/flightloggin/fixtures/profile.json.bz2;

echo "stats";
/srv/flightloggin/manage.py dumpdata site_stats | bzip2 > /srv/flightloggin/fixtures/stats.json.bz2;

echo "columns";
/srv/flightloggin/manage.py dumpdata logbook.columns | bzip2 > /srv/flightloggin/fixtures/logbook.json.bz2;
