BAR_AGG_FIELDS = ('By Person',
                  'By Instructor',
                  'By Captain',
                  'By First Officer',
                  'By Tailnumber',
                  'By Type',
                  'By Manufacturer',
                  'By Category/Class',
                  'By Distance',
                 )
