STATS_TITLES = {
    "users":           ("Total user accounts", "Users"),
    "non_empty_users": ("Number of users with a non-empty logbook", "Users"),
    "total_hours":     ("Total flight hours from all users", "flight hours"),
    "day_wmu":         ("Date where the most unique users edited some part of their logbook","NA"),
    "day_wmh":         ("Date with the most hours logged by all users","NA"),
    "total_logged":    ("Total number of flights logged","Flights"),
    "avg_duration":    ("Average duration of all logged flights","Length of flight in hours"),
    "avg_per_active":  ("Average total hours logged per non-empty-logbook user","Total Logbook Hours"),
    "pwm_hours":       ("The user with the most hours logged has X hours", "Flight Hours"),
    "pwm_count":       ("The user with the most flights logged has X entries", "Number of Flights"),
    "num_7_days":      ("Total number of flights logged in the past 7 days","Number of Flights"),
    "user_7_days":     ("Number of unique users who have logged a flight in the past 7 days","Users"),
    "time_7_days":     ("Total flight hours logged in the past 7 days", "Flight Hours"),
    "unique_airports": ("Total unique airports visited by all users", "Unique Airports"),
    "unique_countries": ("Total unique countries visited by all users", "Unique Countries"),
    "total_dist":      ("Total distance of all routes", "Nautical Miles"),
    "route_earths":    ("Total distance of all routes in Earth Circumferences", "Earths"),
    "unique_tn":       ("Total unique tailnumbers from all users", "Unique Tailnumbers"),
    "most_common_airports": ("Airports visited by the most users", "NA"),
    "most_common_tails": ("Tailnumbers used by the most users", "NA"),
    "most_common_types": ("Most common types", "NA"),
    "most_common_manu": ("Most common manufacturers", "NA"),
}
