#! /bin/bash


export PYTHONPATH=/home/chris/Websites/flightloggin:/home/chris/lib/python2.6
export DJANGO_SETTINGS_MODULE=settings

get='get'

cd /srv/flightloggin/airport;

if [ $1 = $get ]; then

    echo ">>>>>>>> Getting remote airport files...<<<<<<<";

    wget -O - http://www.ourairports.com/data/regions.csv > fixtures/regions.csv;
    wget -O - http://www.ourairports.com/data/countries.csv > fixtures/countries.csv;
    wget -O - http://www.ourairports.com/data/airports.csv > fixtures/airports.csv;
    wget -O - http://www.ourairports.com/data/navaids.csv > fixtures/navaids.csv;

    echo ">>>>>>>>>>>>>>>>>> Diff Below <<<<<<<<<<<<<<<<<";

    git diff $PWD/fixtures/airports.csv;
    git diff $PWD/fixtures/navaids.csv;
    cd -;
fi

echo "$PWD >>>>>>>>>>>> Clearing previous locations <<<<<<<<<<";

wget -q -O - http://localhost:8000/clearlocations.py?sk=dongs;
echo

echo ">>>>>>>>>> Running Import script... <<<<<<<<<<<";

python $PWD/imports.py
