#! /bin/bash


export PYTHONPATH=/home/chris/Websites/flightloggin:/home/chris/lib/python2.6
export DJANGO_SETTINGS_MODULE=settings

get='get'

if [ $1 = $get ]; then

    echo ">>>>>>>> Getting remote airport files...<<<<<<<";

    wget -O - http://www.ourairports.com/data/regions.csv > ~/Websites/flightloggin/airport/fixtures/regions.csv;
    wget -O - http://www.ourairports.com/data/countries.csv > ~/Websites/flightloggin/airport/fixtures/countries.csv;
    wget -O - http://www.ourairports.com/data/airports.csv > ~/Websites/flightloggin/airport/fixtures/airports.csv;
    wget -O - http://www.ourairports.com/data/navaids.csv > ~/Websites/flightloggin/airport/fixtures/navaids.csv;

    echo ">>>>>>>>>>>>>>>>>> Diff Below <<<<<<<<<<<<<<<<<";

    cd ~/Websites/flightloggin/;
    git diff /home/chris/Websites/flightloggin/airport/fixtures/airports.csv;
    git diff /home/chris/Websites/flightloggin/airport/fixtures/navaids.csv;
    cd -;
fi

echo ">>>>>>>>>>>> Clearing previous locations <<<<<<<<<<";

wget -q -O - http://localhost:8000/clearlocations.py?sk=dongs;
echo

echo ">>>>>>>>>> Running Import script... <<<<<<<<<<<";

python ~/Websites/flightloggin/airport/imports.py
