#! /bin/bash

cd fixtures

wget http://www.ourairports.com/data/regions.csv;
wget http://www.ourairports.com/data/countries.csv;
wget http://www.ourairports.com/data/airports.csv;
wget http://www.ourairports.com/data/navaids.csv;
