#! /bin/bash

cd csv

wget -O - http://www.ourairports.com/data/regions.csv > regions.csv;
wget -O - http://www.ourairports.com/data/countries.csv > countries.csv;
wget -O - http://www.ourairports.com/data/airports.csv > airports.csv;
wget -O - http://www.ourairports.com/data/navaids.csv > navaids.csv;

./clean_airport_csv.py
